googletest_framework_root = "/home/amoe/vcs/googletest"

googletest_include_paths = [
    googletest_framework_root + "/googletest",
    googletest_framework_root + "/googletest/include",
    googletest_framework_root + "/googlemock",
    googletest_framework_root + "/googlemock/include"
]

gtest_all_path = googletest_framework_root + "/googletest/src/gtest-all.cc"
gmock_all_path = googletest_framework_root + "/googlemock/src/gmock-all.cc"

env = Environment(CPPPATH=googletest_include_paths)

gtest_obj = env.Object(gtest_all_path)
gmock_obj = env.Object(gmock_all_path)

env.Program(
    target='tests_chapter3',
    source=Glob('chapter3/*.cc') + [gtest_obj, gmock_obj],
    LIBS=['pthread']
)

# env.Program(
#     target='tests_chapter4',
#     source=Glob('chapter4/*.cc') + [gtest_all_path, gmock_all_path],
#     LIBS=['pthread']
# )
